server:
  port: 8084

spring:
  application:
    name: report-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:report_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

aws:
  region: ${AWS_REGION:us-east-1}
  sqs:
    analysis-completed-queue-url: ${AWS_SQS_ANALYSIS_COMPLETED_QUEUE_URL:http://localhost:4566/000000000000/analysis-completed-queue-dev}
  endpoint: ${AWS_ENDPOINT:}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true

aws:
  endpoint: http://localhost:4566

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false

aws:
  endpoint: ""
